name: objectgs
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.8.19
  - pip=24.2
  - pytorch=2.1.2
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - pytorch-cuda=11.8
  - pytorch-scatter
  - pip:
    - plyfile
    - tensorboard
    - tqdm
    - einops
    - imageio
    - matplotlib
    - kornia
    - wandb
    - lpips
    - laspy
    - jaxtyping
    - colorama
    - opencv-python
    - scikit-learn
    - git+https://github.com/RuijieZhu94/gsplat-object.git
